# Site settings
title: Ken Kelly - Web Developer
email: ken@kenhkelly.us
description: > # this means to ignore newlines until "baseurl:"
  I am a Web Developer &amp; Internet Marketer. I deliver beautifully crafted projects with passion.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenhkelly.us" # the base hostname & protocol for your site
twitter_username: kenhkelly
github_username:  kenhkelly
# paginate: 5
# paginate_path: "/blog/page:num/"
exclude: [README.md, deploy.sh]
timezone: America/New_York

# Build settings
markdown: kramdown

# Outputting
permalink:  /:year/:month/:title